WebApp/Controllers/BidController.cs
using AutoMapper;
using BusinessAccess;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using SharedLibrary;

namespace WebApp
{
    [Route("bid")]
    public class BidController : Controller
    {
        private readonly BidManager bidManager;
        private readonly IMapper mapper;

        public BidController(BidRepository repository, IMapper mapper, IEmailService emailService)
        {
            bidManager = new BidManager(repository, mapper, emailService);
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            var bids = bidManager.GetBidsByCustomerId(User.GetUserId());
            return View(bids);
        }



        [HttpPost("createbid")]
        public IActionResult CreateBid(BidRequest bidRequest)
        {
            var userId = User.GetUserId();
            var returnVal = bidManager.GetBidsByCustomerId(userId);
            if (ModelState.IsValid)
            {
               // var userId = User.GetUserId();
                var res = bidManager.CreateBid(bidRequest, userId);
                var bids = bidManager.GetBidsByCustomerId(userId);
                return PartialView("_BidListPartial", bids);

            }
            else
            return PartialView("_BidListPartial", returnVal);


        }

        [HttpGet("deletebid")]
        public IActionResult Deletebid(Guid id)
        {
            var returnval = bidManager.DeleteBid(id);
            return RedirectToAction(nameof(Index), returnval);
        }


        [HttpPost("updatebid")]
        public IActionResult UpdateBid(BidResponse bidRequest)
        {
            var val = bidManager.UpdateBid(bidRequest);
            return RedirectToAction(nameof(Index));
        }


        [HttpGet("viewbids")]
        public IActionResult ViewBids()
        {
            var allbids = bidManager.GetAllbids();
            return View(allbids);
        }

        [HttpPost("addpartcipant")]
        public IActionResult AddPartcipant(Guid bidId,string bidRate)
        {
            if (ModelState.IsValid)
            {
                PartcipantRequest partcipantRequest = new()
                {
                    Id = Guid.NewGuid(),
                    PartcipantId = User.GetUserId(),
                    BidId = bidId,
                    BidRate = bidRate,
                };
                ViewBag.reVal = bidManager.AddPartcipant(partcipantRequest);
            }
            return View();
        }


        [HttpGet("participantbid")]
        public IActionResult ParticipantBid()
        {
            var myBids = bidManager.GetBidsByParticipantId(User.GetUserId());
            return View(myBids);
        }
    }
}

WebApp/Views/Bid/AddPartcipant.cshtml
<link rel="stylesheet" href="~/css/Animation.css" />

@if (ViewBag.reVal == -1)
{
    <div style="text-align:center;font-weight:bolder;" class="alert alert-danger">You Have Already Request For This!</div>
}
else
{
    <div class="wrapper">
        <svg class="animated-check" viewBox="0 0 24 24">
            <path d="M4.1 12.7L9 17.6 20.3 6.3" fill="none" />
        </svg>
        <h6 style="margin-top:auto;margin-bottom:200px;margin-right:20px">
            Your Request Has Been Sucessfully Sent To Customer
        </h6>

    </div>
}

WebApp/Views/Bid/Index.cshtml
@model IEnumerable<BidResponse>
@{
    //Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<div class="container" style="margin-left:20px">
    
    <div>
        <partial name="_CreateBidPartial" model="new BidRequest()"></partial>
    </div>
    <div>
    </div>
    <div id="partialBidData">
        <partial name="_BidListPartial" model="Model"></partial>
    </div>
</div>


    
@section Scripts
{
         <script type="module" src="~/client/bidService .js" asp-append-version="true"></script>
}

WebApp/Views/Bid/ParticipantBid.cshtml
@model IEnumerable<Models.BidResponse>

@{
    ViewData["Title"] = "ParticipantBid";
}

<h1>My Bids</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.BidType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BidNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BidRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.BidStatus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.BidType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BidNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BidRate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.BidStatus)
            </td>
        </tr>
}
    </tbody>
</table>

WebApp/Views/Bid/ViewBids.cshtml
@model IEnumerable<BidShowRequest>

@*USER CARDS STRATS HERE*@
<link rel="stylesheet" href="~/css/Card.css" />
<div class="container-fluid pt-4 px-4 ">

    @{
        foreach (var item in Model)
        {
            <div class="section_our_solution">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="our_solution_category">
                            <div class="solution_cards_box col-6" style="margin-left:10%;min-width:70%;max-width:70%;width:70%;">
                                <div class="solution_card" style="overflow-y:scroll;">
                                    <div class="hover_color_bubble"></div>
                                    <div class="so_top_icon">
                                        <svg id="Layer_1" enable-background="new 0 0 512 512" height="50" viewBox="0 0 512 512" width="40" xmlns="http://www.w3.org/2000/svg">
                                            <g>
                                                <g>
                                                    <g>
                                                        <g>
                                                            <path d="m47.478 452.317 295.441 19.76c5.511.369 10.277-3.8 10.645-9.31l28.393-424.517c.369-5.511-3.8-10.276-9.31-10.645l-295.441-19.76c-5.511-.369-10.276 3.8-10.645 9.31l-28.394 424.517c-.368 5.511 3.8 10.277 9.311 10.645z" fill="#fae19e" />
                                                        </g>
                                                        <g>
                                                            <g>
                                                                <g>
                                                                    <g>
                                                                        <g>
                                                                            <path d="m17.5 504.177h226.14l79.96-79.605v-355.86c0-5.523-4.477-10-10-10h-296.1c-5.523 0-10 4.477-10 10v425.466c0 5.522 4.477 9.999 10 9.999z" fill="#fff9e9" />
                                                                        </g>
                                                                        <path d="m313.601 58.712h-40c5.523 0 10 4.477 10 10v355.861l-.258 40.078 40.258-40.078v-355.861c0-5.523-4.477-10-10-10z" fill="#fff4d6" />
                                                                    </g>
                                                                </g>
                                                            </g>
                                                            <path d="m243.64 504.177v-70.253c0-5.523 4.477-10 10-10h69.96z" fill="#ffeec2" />
                                                        </g>
                                                    </g>
                                                    <g>
                                                        <path d="m468.636 248.58-33.372.165v-50.826c0-9.183 7.463-16.662 16.673-16.708h.007c9.217-.046 16.693 7.371 16.693 16.562v50.807z" fill="#fed23a" />
                                                        <path d="m451.96 504.177c-10.362-10.277-16.196-24.263-16.208-38.857l-.062-73.973c0-.644.524-1.169 1.171-1.173l30.038-.149c.647-.003 1.171.517 1.171 1.161l.062 74.079c.012 14.531-5.749 28.472-16.015 38.756z" fill="#54b1ff" />
                                                        <path d="m451.959 469.333h-.01c-14.434.072-26.14-11.542-26.14-25.935v-213.527c0-6.778 5.477-12.283 12.255-12.316l27.626-.137c6.826-.034 12.378 5.49 12.378 12.316v213.436c0 14.38-11.687 26.091-26.109 26.163z" fill="#fdf385" />
                                                        <path d="m465.69 217.417-23.769.118c6.037.79 10.708 5.94 10.708 12.198v213.437c0 9.823-5.455 18.397-13.507 22.87 3.79 2.115 8.164 3.317 12.826 3.293h.01c14.422-.072 26.109-11.783 26.109-26.163v-213.436c.001-6.826-5.551-12.351-12.377-12.317z" fill="#faee6e" />
                                                        <path d="m491.274 247.925-71.615.355c-7.305.036-13.226 5.968-13.226 13.248 0 7.281 5.921 13.153 13.226 13.117l58.389-.29v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c0-7.28-5.922-13.152-13.226-13.116z" fill="#54b1ff" />
                                                        <g>
                                                            <path d="m491.274 247.925-38.441.188-.167 26.311 25.381-.067v77.489c0 7.281 5.921 13.153 13.226 13.117 7.305-.036 13.226-5.968 13.226-13.248v-90.672c.001-7.282-5.921-13.154-13.225-13.118z" fill="#3da7ff" />
                                                        </g>
                                                    </g>
                                                </g>
                                                <g fill="#060606">
                                                    <path d="m373.147 20.122-295.44-19.761c-9.631-.638-17.984 6.665-18.629 16.293l-2.311 34.557h-39.267c-9.649 0-17.5 7.851-17.5 17.5v425.466c0 9.649 7.851 17.5 17.5 17.5h226.141c1.96 0 3.902-.801 5.292-2.185l34.138-33.987c.347.074.701.133 1.065.157l58.282 3.898c9.302.614 18.005-6.952 18.629-16.293l28.393-424.515c.639-9.528-6.766-17.993-16.293-18.63zm-122.006 465.902v-52.1c0-1.378 1.122-2.5 2.5-2.5h51.9zm94.939-23.757c-.244 1.51-1.131 2.286-2.66 2.327l-46.28-3.096 31.752-31.611c1.414-1.407 2.209-3.32 2.209-5.315v-355.86c0-9.649-7.851-17.5-17.5-17.5h-77.993c-9.697 0-9.697 15 0 15h77.993c1.379 0 2.5 1.122 2.5 2.5v347.712h-62.46c-9.649 0-17.5 7.851-17.5 17.5v62.753h-218.641c-1.378 0-2.5-1.122-2.5-2.5v-425.465c0-1.378 1.122-2.5 2.5-2.5h178.168c9.697 0 9.697-15 0-15h-123.868l2.244-33.556c.244-1.511 1.131-2.286 2.661-2.327l295.44 19.76c1.511.244 2.287 1.131 2.328 2.661z" />
                                                    <path d="m267.827 237.047h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z" />
                                                    <path d="m267.827 289.332h-204.553c-4.142 0-7.5 3.358-7.5 7.5s3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5z" />
                                                    <path d="m55.774 192.262c0 4.142 3.358 7.5 7.5 7.5h204.553c4.143 0 7.5-3.358 7.5-7.5s-3.357-7.5-7.5-7.5h-204.553c-4.142 0-7.5 3.358-7.5 7.5z" />
                                                    <path d="m91.807 139.977c0 4.142 3.358 7.5 7.5 7.5h132.487c4.142 0 7.5-3.358 7.5-7.5s-3.358-7.5-7.5-7.5h-132.487c-4.142 0-7.5 3.358-7.5 7.5z" />
                                                    <path d="m194.755 438.787c-13.489.036-26.978.065-40.467.086-4.534.007-9.067.013-13.6.016-8.215.006-13.75-1.643-15.59-10.679-1.556-7.64-12.364-6.613-14.464 0-5.19 16.337-13.774 9.936-18.582-1.053-4.797-10.963-6.027-23.233-8.122-34.9-1.54-8.573-14.506-6.17-14.732 1.994-.298 10.751-1.302 21.331-4.031 31.758-2.815 10.758-7.034 21.097-11.222 31.376-3.651 8.961 10.867 12.816 14.464 3.988 3.711-9.108 7.427-18.266 10.193-27.714 5.14 12.36 15.774 26.34 30.927 18.101 2.819-1.533 5.452-3.712 7.763-6.253 7.88 9.106 19.609 8.388 30.584 8.375 15.627-.02 31.254-.054 46.881-.095 9.649-.025 9.667-15.025-.002-15z" />
                                                    <path d="m505.932 246.439c-3.897-3.878-9.255-5.867-14.695-6.014l-5.668.028v-10.719c0-6.529-3.878-13.427-9.433-16.862v-15.098c0-31.069-48.372-30.934-48.372.146v15.1c-5.659 3.498-9.455 9.741-9.455 16.852v10.982c-24.966 1.7-25.037 39.745.028 41.232.16 33.575.152 66.6-.028 100.737-.049 9.414 14.949 9.966 15 .079.18-34.166.188-67.22.029-100.823l37.211-.185s-.048 110.848-.048 160.784c0 24.338-37.219 24.5-37.219-.253l.013-13.677c.585-9.68-14.387-10.583-14.973-.904v12.834c0 11 3.402 20.316 9.988 26.869.586 15.693 7.198 30.878 18.369 41.956 3.205 3.18 7.642 2.208 10.744-.182 11.365-11.385 17.769-26.394 18.169-42.414 4.951-4.931 9.908-9.896 9.908-26.896l.006-68.351c12.97 3.689 26.494-6.348 26.494-19.946v-90.672c0-5.523-2.155-10.709-6.068-14.603zm-72.623-5.727v-10.841c0-2.219 1.523-4.08 3.573-4.633l30.025-.149c.84.208 1.615.605 2.243 1.231.915.911 1.419 2.123 1.419 3.414v10.794zm18.671-52c4.604 0 9.155 4.514 9.155 9.062v12.166l-18.372.091v-12.111c.001-5.053 4.133-9.183 9.217-9.208zm-.011 303.901c-3.487-4.942-6.009-10.531-7.417-16.406 2.322.503 4.674.765 7.027.765 2.627 0 5.253-.326 7.839-.957-1.374 5.964-3.892 11.587-7.449 16.598zm45.031-140.899c0 7.101-11.452 7.66-11.452.131 0 0 .013-70.974.021-77.48.005-4.196-3.483-7.509-7.558-7.509l-58.389.29c-7.242 0-7.073-11.331.074-11.366l71.615-.355c3.463.295 5.359 2.168 5.688 5.617v90.672z" />
                                                </g>
                                            </g>
                                        </svg>
                                    </div>
                                    <div class="solu_title">
                                        <h3>@item.BidType</h3>
                                    </div>
                                    <div class="solu_description">
                                        <div class="row">
                                            <div class="col-6">
                                                <div><b>Bid Number</b></div>@item.BidNumber
                                            </div>
                                            <div class="col-6" style="">
                                                <div><b>Bid Rate</b></div>@item.BidRate
                                            </div>


                                            <div class="col-6"><div><b>Address</b></div>@item.Address</div>
                                            <div class="col-6"><div><b> About Bid </b></div><span class="test" >@item.Discription</span></div>

                                            <div class="col-12 text-center mt-5 mb-5 " style="color:green"><div><b> Customer Details </b></div><span class="test" ></span></div>


                                            <div class="col-6"><div><b>UserName</b></div>@item.UserName</div>
                                            <div class="col-6"><div><b>Email </b></div><span class="test" >@item.Email</span></div>
                                            <div class="col-6"><div><b>Phone Number</b></div>@item.PhoneNo</div>

                                            <div class="col-12 text-center mt-5 mb-5 " style="color:brown "><div><b> Want To Offer ? </b></div><span class="test" ></span></div>
                                            <form asp-action="AddPartcipant" asp-controller="Bid" method="post">
                                                <div class="col-12 row">
                                                <input hidden name="bidid" value="@item.Id" />
                                                    <div class="col-10">
                                                        <label for="rate" class="text-center" style="color:CaptionText">Your Rate</label>
                                                        <input type="text" name="bidrate" id="rate" class="form-control">
                                                    </div>
                                                    <div class="col-2">
                                                        <label class="text-center" style="color:CaptionText">Action</label><br>
                                                        
                                                        <button class="btn btn-outline-primary">Offer</button>
                                                    </div>
                                                </div>
                                            </form>



                                        </div>
                                       
                                </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

          

        }
    }
</div>
@*USER CARDS ENDS HERE*@

WebApp/Views/Bid/_BidListPartial.cshtml
@model IEnumerable<BidResponse>


<head>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<style>

</style>

@if (Model != null && Model.Count() > 0)
{
    <div id="partialData" class=" @* mt-5 mb-3 *@ col-12">
        <div class="row">

            @foreach (var item in Model)
            {
                if (item.BidStatus == BidStatus.Pending)
                {

                    <form asp-action="updatebid" asp-controller="bid" method="post"  style="margin-top:20px;background-color:#cffaf4">
                        <div class="row">
                             <input name="Id" hidden  value="@item.Id" />
                             @*<input hidden asp-for="@item.Id" class="form-control">*@
                            <div class="col-6">
                                <div class="form-group ">
                                    <label asp-for="@item.BidNumber">Bid Number</label>
                                    <input  name="BidNumber" asp-for="@item.BidNumber" readonly class="form-control">
                                </div>
                                <div class="form-group ">
                                    <label asp-for="@item.BidRate">Bid Rate</label>
                                    <input  name="BidRate" asp-for="@item.BidRate" class="form-control">
                                </div> 
                               
                            </div>
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@item.BidType">Bid Type</label>
                                    <input name="BidType" asp-for="@item.BidType" class="form-control">
                                </div> 
                                <div class="form-group">
                                    <label asp-for="@item.BidStatus">Bid Status</label>
                                    <input name="BidStatus" asp-for="@item.BidStatus" readonly class="form-control">
                                </div>
                            </div>
                             <div class="form-group ">
                                    <label asp-for="@item.Address">Address</label>
                                    <input name="Address" asp-for="@item.Address" class="form-control">
                                </div>
                            <div class="form-group">
                                <label asp-for="@item.Discription">Discription</label>
                                <textarea name="Discription" class="form-control" asp-for="@item.Discription" rows="3"></textarea>
                            </div>
                            <div class="form-group col-6 ">
                                <div>
                                <button type="submit" class="btn btn-info">Update</button>
                                </div>
                                <div>
                                    <a asp-action="deletebid" style="display: inline-flex;background-color: red;margin-left: 900px;margin-top: -62px;" class="btn btn-danger" asp-controller="bid" asp-route-id="@item.Id">Delete</a>
                                </div>
                            </div>
                        </div>

                    </form>


                }
                else if (item.BidStatus == BidStatus.Accepted)

                {

                    <div class="  col-6">
                        <div class="card p-3 mb-2">
                            <div class="d-flex justify-content-between">
                                <div class="d-flex flex-row align-items-center">
                                    <div class="icon"> <i class="bx bxl-mailchimp"></i> </div>
                                    <div class="ms-2 c-details">
                                        <h6 class="mb-0">@item.BidRate</h6> <span>@item.BidType</span>
                                    </div>
                                    <div class="badge"><span>@item.BidNumber</span></div>
                                </div>
                                <div>
                                    <h6 class="heading" style="color:#ff66b3;">@item.BidStatus<br></h6>

                                </div>

                                <div class="mt-5">
                                    <h5 class="heading">@item.Discription<br></h5>
                                    <div class="mt-5">

                                        <div class="mt-3"> <span class="text1">32 Applied <span class="text2">of 50 capacity</span></span> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            }
        </div>
    </div>
}
@*
    <script>

    $(document).ready(function(){
    document.getElementById("heart").onclick = function(){
    document.querySelector(".fa-gratipay").style.color = "#E74C3C";
    };
    });
    </script>*@

WebApp/Views/Bid/_CreateBidPartial.cshtml
@model BidRequest


@{
    Layout = null;
}


<div>
    <div class="row ">
        <div class="col-md-12" >
            <form asp-action="createbid" asp-controller="bid" method="post" id="postForm">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="BidType" class="control-label"></label>
                    <input asp-for="BidType" class="form-control" />
                    <span asp-validation-for="BidType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Discription" class="control-label"></label>
                   <textarea asp-for="Discription" class="form-control" rows="4" cols="60">
                     </textarea>
                    <span asp-validation-for="Discription" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <label asp-for="BidRate" class="control-label"></label>
                    <input asp-for="BidRate" class="form-control" />
                    <span asp-validation-for="BidRate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    </div>