WebApp/Controllers/AdminController.cs
using AutoMapper;
using BusinessAccess;
using DataAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using SharedLibrary;

namespace WebApp
{
    [Route("admin")]
    public class AdminController : Controller
    {
        private readonly AdminManager adminManager;
        private readonly AccountManager accountManager;

        public AdminController(AccountRepository repository,IEmailService emailService,IMapper mapper)
        {
            adminManager = new AdminManager(repository,emailService);
            accountManager = new AccountManager(repository,emailService,mapper);
        }


        public IActionResult Index()
        {
            return View();
        }


        [HttpGet("dashboard")]
        public IActionResult DashBoard()
        {
           var users= accountManager.GetAllUsers();
            return View(users);
        }
        

   
        [HttpGet("Search")]
        public IActionResult SearchBox(string searchString)
        {
            var users = accountManager.GetAllUsers();
           // var users = accountManager.SearchUserBy(searchString);
            return View(users);
        }


        [HttpGet("users")]
        public IActionResult AllUsers()
        {
            var allUsers = accountManager.GetAllUsers();
            return View(allUsers);    
        }


        [HttpGet("details/{Id}")]
        public IActionResult GetDetailsById(Guid Id)
        {
           var user= accountManager.GetAllUsers().FirstOrDefault(x => x.Id == Id);
            return View(user);
        }


        [HttpGet("create")]
        public IActionResult CreateUser()
        {
            ViewBag.Managers = adminManager.GetAllManagers();
            return View();
        }

        [HttpPost("create")]
        public IActionResult CreateUser(SignupRequest signupRequest)
        {
            if (ModelState.IsValid)
            {
                var result = adminManager.CreateUser(signupRequest);
                if (result == -2)
                    ViewBag.Message = -2;
                else
                    if (result == -1)
                    ViewBag.Message = -1;
                else
                    if (result > 0)
                    ViewBag.Message = 1;
            }
            
            return View();
        }
        

        [HttpGet("getuserby/{searchString?}/{roleValue?}")]
        public PartialViewResult getuserby(string searchString,UserRole roleValue)
        {


            SearchBox(searchString);
            if (roleValue == 0)
            {
                var users = accountManager.SearchUserBy(searchString);

                return PartialView("_searchPartial", users);
            }
            else
            {
                var users = accountManager.SearchUserBy(searchString);
                var filteredOnRoleUsers=users.Where(x => x.UserRole == roleValue);

                return PartialView("_searchPartial", filteredOnRoleUsers);
            }
            

        }

        [HttpGet("getallusersbyrole/{roleVal?}")]
        public PartialViewResult GetAllUsersByRole(UserRole roleVal)
        {
            var users = accountManager.GetAllUsers().Where(x => x.UserRole == roleVal);
            return PartialView("_searchPartial", users);

        }

        [HttpGet("messages")]
        public IActionResult GetAllMessages()
        {
            var allMessages = adminManager.GetAllMessages();
            return View(allMessages);
        }


        [HttpGet("testimonial")]
        public IActionResult Testimonial()
        {
            var testimonials = adminManager.GetTestimonial();
            return View(testimonials);
        }

        [HttpGet("managers/{userRole?}")]
        public JsonResult GetRoles(UserRole userRole)
        {
            var roles=adminManager.GetRoles(userRole);
            return Json(roles);
        }

        [HttpPost("changestatus")]
        public IActionResult ChangeStatus(Guid id)
        {
            adminManager.ChangeUserStatus(id);
            return RedirectToAction(nameof(SearchBox));
        }
    }
}

WebApp/Controllers/SliderController.cs
using BusinessAccess;
using DataAccess;
using Microsoft.AspNetCore.Mvc;

using Models;
using System.Net;

namespace WebApp
{
    public class SliderController : Controller
    {

        private readonly SliderManager sliderManager;
        private readonly IWebHostEnvironment Environment;
        public SliderController(IRepository repository, IWebHostEnvironment environment)
        {
            sliderManager = new SliderManager(repository);
            Environment = environment;
        }

        
        public IActionResult Index()
        {
            var sliders = sliderManager.GetSliders();
            return View(sliders);
        }

        
        
        [HttpPost]
        public IActionResult AddSlider(SliderRequest sliderRequest)
        {
            if (ModelState.IsValid)
            {
                var message = sliderManager.AddSlider(sliderRequest, Environment.WebRootPath);
                if (message != "Success")
                {
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(message);
                }

                return PartialView("_SliderPartial", sliderManager.GetSliders());
            }
            Response.StatusCode = (int)HttpStatusCode.BadRequest;
            return RedirectToAction(nameof(Index));
        }


        public IActionResult deleteslider(Guid id)
        {
            if (true)
            {

            }
            var response = sliderManager.DeleteSlider(id, Environment.WebRootPath);
            return RedirectToAction(nameof(Index));
        }





        //public iactionresult update()
        //{
        //    return view();
        //}

    }
}   

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>WorkForce</title>


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,700,700i&display=swap"
          rel="stylesheet">

    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/js/bootstrap.bundle.js">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/css/userSearchDetails.css" rel="stylesheet">
    @*

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    *@
    <link href="https://fonts.googleapis.com/css?family=Assistant:400,700" rel="stylesheet">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- <link href="assets/vendor/animate.css/animate.css"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
            crossorigin="anonymous"></script>
    <link href="~/css/style.css" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center header-transparent" style="background-color: #0b212d">
        <div class="container d-flex justify-content-between align-items-center">

            <div class="logo">
                <h1 class="text-light">
                    <a asp-action="Index" asp-controller="Home">
                        <img src="~/Images/pngegg.png" alt=""
                             class="img-fluid"><span>WorkForce</span>
                    </a>
                </h1>
            </div>
            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="active " asp-action="Index" asp-controller="Home">Home</a></li>
                    <li><a asp-action="AboutUs" asp-controller="Home">About</a></li>

                    <li class="dropdown">
                        <a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a href="#">Drop Down 1</a></li>
                            <li><a href="#">Drop Down 2</a></li>
                            <li><a href="#">Drop Down 3</a></li>
                            <li><a href="#">Drop Down 4</a></li>
                        </ul>
                    </li>
                    <li><a asp-action="ContactUs" asp-controller="Home">Contact us</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {

                    }
                    else
                    {
                        <li><a asp-action="login" asp-controller="Account">Login</a></li>
                        <li><a asp-action="SignUp" asp-controller="Account">Signup</a></li>
                    }
                    <!-- Button trigger modal -->
                    <!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                     modal
                    </button>

                     Modal
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            ...
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                          </div>
                        </div>
                      </div>
                    </div> -->
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole(UserRole.Admin.ToString()))
                        {
                            <li><a asp-action="Dashboard" asp-controller="Admin">Go to ExternalSite</a></li>
                        }


                        if (User.IsInRole(UserRole.Contractor.ToString()))
                        {
                            <li><a asp-action="" asp-controller="">Go to ExternalSite</a></li>
                        }


                        if (User.IsInRole(UserRole.Customer.ToString()))
                        {
                            <li><a asp-action="" asp-controller="">Go to ExternalSite</a></li>
                        }

                        if (User.IsInRole(UserRole.Labour.ToString()))
                        {
                            <li><a asp-action="" asp-controller="">Go to ExternalSite</a></li>
                        }

                        if (User.IsInRole(UserRole.Manager.ToString()))
                        {
                            <li><a asp-action="" asp-controller="">Go to ExternalSite</a></li>
                        }
                    }


                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
            <!-- navbar  -->

        </div>
    </header>

    <main role="main">
        @RenderBody()
    </main>


    <!-- ======= Footer ======= -->
    <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Service 1</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Service 2</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Service 3</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Service 4</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Service 5</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h4>Contact Us</h4>
                        <p>
                            Pulwama Kmr <br>
                            pulwama <br>
                            India <br><br>
                            <strong>Phone:</strong> 12345677<br>
                            <strong>Email:</strong> workforce@@yopmail.com<br>
                        </p>

                    </div>

                    <div class="col-lg-3 col-md-6 footer-info">
                        <h3>About WorkForce</h3>
                        <p>
                            Many novice writers tend to make a sharp distinction between content and style, thinking that a paper can
                            be strong in one and weak in the other.
                        </p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>WorkForce</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>

    <!-- JS Files -->

    <script src="~/vendor/aos/aos.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- <script src="assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="assets/bootstrap-icons/bootstrap-icons.json"></script> -->
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/js/main.js"></script>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>


</html>

WebApp/Views/Shared/_TestimonialPartial.cshtml
@model TestimonialRequest

@{
    var x = ViewBag.returnValue;
    if (x != null)
    {
        if (x > 0)
        {
            <script>
                swal("Feedback Sent", "Feedback Shared successfully", "success");
            </script>

        }
        else
        {
            <script>
                swal("Message not sent", "There is some issue", "error");
            </script>
        }
    }
}

<div class="container" style="margin-top:100px; text-align:center;">
    <h2>
        Your Feedback
    </h2>
    <div class="container mb-2" >
        <form method="post" asp-action="Testimonial" asp-controller="Testimonial">
            <input asp-for="Id" class="form-control" hidden>

            <div class=" form-group">
                <input asp-for="Name" readonly value=@User.GetUserName() class="form-control">
            </div>
            <div class="form-group mt-3">
                <textarea asp-for="FeedbackMessage" class="form-control" rows="5" placeholder="Share Your Feedback" required="required"></textarea>
            </div>

            <div>
                <input asp-for="ImagePath" hidden value=@User.GetImagePath()/>
            </div>
            <div>
                <select class="form-control" asp-items="@Html.GetEnumSelectList<UserRole>()" hidden>
                </select>
            </div>


            <div class="text-center"><button type="submit" class="btn btn-primary mt-2">Share Feedback</button></div>
        </form>
    </div>

</div>

WebApp/Views/Shared/_UserLayout.cshtml
@if (User.Identity.IsAuthenticated)
{
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8">
        <title>@User.GetRole()</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

        <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

        <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
        <link rel="stylesheet" href="bower_components/sweetalert2/dist/sweetalert2.min.css">

        <!-- Libraries Stylesheet -->
    <link href="~/AdminFiles/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="~/AdminFiles/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

        <!-- Customized Bootstrap Stylesheet -->
    <link href="~/AdminFiles/css/bootstrap.min.css" rel="stylesheet">

        <!-- Template Stylesheet -->
    <link href="~/AdminFiles/css/style.css" rel="stylesheet">

        <link rel="stylesheet" href="~/Client/services/tata-master/dist/index.css">

    </head>

    <body>
        <!--Nav Bar Admin-->

    <div class="container-xxl position-relative bg-white d-flex p-0">
            <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
                <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
            <!-- Spinner End -->
            <!-- Sidebar Start -->
        <div style="background-color:#0b212d" class="sidebar pe-4 pb-3">
                <nav style="background-color:#0b212d" class="navbar navbar-light">
                    <a href="#" class="navbar-brand mx-4 mb-3">
                        <a asp-action="index" asp-controller="home"><h3 class="text-primary"><i class="fa fa-hashtag me-2"></i>WorkForce</h3></a>
                    </a>
                    <div class="d-flex align-items-center ms-4 mb-4">
                        <div class="position-relative">
                            <img class="rounded-circle" src="@User.GetImagePath()" alt="" style="width: 40px; height: 40px;">
                            <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                        </div>
                        <div class="ms-3">
                            <h6 class="mb-0 text-light">@User.GetUserName().ToUpper()</h6>
                            <span class="text-success">@User.GetRole()</span>
                        </div>
                    </div>
                    <div class="navbar-nav w-100">

                        @*@if (User.IsInRole(UserRole.Faculty.ToString()) || User.IsInRole(UserRole.HOD.ToString()))
                            {
                            <a asp-controller="Employee" asp-action="Index" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                            <a asp-action="Index" asp-controller="Question" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Question Bank</a>
                            <a asp-controller="paper" asp-action="create" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Add Paper</a>
                            <a asp-controller="paper" asp-action="getpapers" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Papers</a>
                            }*@
                        @if (User.IsInRole(UserRole.Admin.ToString()))
                        {
                            <a asp-controller="Admin" asp-action="Dashboard" class="nav-item nav-link text-light "><i style="color:black" class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                            <a asp-action="Index" asp-controller="Slider" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>Add Slider</a>
                            <a asp-action="Search" asp-controller="Admin" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>Users</a>
                            <a asp-action="messages" asp-controller="Admin" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>Feedback</a>
                            <a asp-action="Testimonial" asp-controller="Admin" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>Testimonial</a>
                            <a asp-action="Create" asp-controller="admin" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-table me-2"></i>Add User</a>


                        }
                        @if (User.IsInRole(UserRole.Manager.ToString()) || User.IsInRole(UserRole.Contractor.ToString()) || User.IsInRole(UserRole.Labour.ToString()))
                        {
                            <a asp-action="assignedlabours" asp-controller="Manager" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-table me-2"></i>Attendance</a>
                            <a asp-action="viewbids" asp-controller="bid" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>View Bids</a>
                        }


                        @if (User.IsInRole(UserRole.Customer.ToString()))
                        {
                            <a asp-action="Index" asp-controller="bid" class="nav-item nav-link text-light "><i style="color:black" class="fa fa-th me-2"></i>Add Bids</a>
                        }


                        <a asp-action="changepassword" asp-controller="Account" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>Change Password</a>
                        <a asp-action="logout" asp-controller="Account" class="nav-item nav-link text-light"><i style="color:black" class="fa fa-th me-2"></i>Logout</a>

                    </div>
                </nav>
            </div>
            <!-- Sidebar End -->
            <!-- Content Start -->
        <div class="content">
                <!-- Navbar Start -->
            <nav style="background-color:#0b212d" class="navbar navbar-expand navbar-light sticky-top px-4 py-0">
                    <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                        <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                    </a>
                    <a href="#" class="sidebar-toggler flex-shrink-0">
                        <i class="fa fa-bars"></i>
                    </a>

                    <div class="navbar-nav align-items-center ms-auto">
                        @if (User.IsInRole(nameof(UserRole.Admin)))
                        {
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                                    <i class="fa fa-envelope me-lg-2"></i>
                                    <span style="color:white" class="d-none d-lg-inline-flex">Message</span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0" style="max-height:300px;overflow-y:scroll;z-index:100000;min-height:50px">
                                    @*@await Component.InvokeAsync("ContactMessage")*@
                                </div>
                            </div>

                        }
                         <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                               
                                <img class="rounded-circle me-lg-2" src="@User.GetImagePath()" alt="" style="width: 40px; height: 40px;">
                                <span style="color:white" class="d-none d-lg-inline-flex">@User.GetUserName().ToUpper()</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                                @if (User.IsInRole(UserRole.Admin.ToString()))
                                {
                                    <a asp-action="EditAdmin" asp-controller="Account" class="dropdown-item">My Profile</a>
                                }
                                 @if (User.IsInRole(UserRole.Manager.ToString()) || User.IsInRole(UserRole.Labour.ToString()) || User.IsInRole(UserRole.Customer.ToString()) || User.IsInRole(UserRole.Contractor.ToString()))
                                {
                                    <a asp-action="Profile" asp-controller="Account" class="dropdown-item">My Profile</a>
                                }
                                <a asp-action="logout" asp-controller="Account" class="dropdown-item">Logout</a>
                                <a asp-action="index" asp-controller="Home" class="dropdown-item">GoTo External Site</a>

                            </div>
                        </div>
                    </div>
                </nav>
                <!-- Navbar End -->
                <!-- Body -->
            @RenderBody()
                <!-- Body End -->
        </div>
            <!-- Content End -->
            <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
        </div>

        <script>

            let searchBox =  document.getElementById("search");
            searchBox.addEventListener("keyup",()=>{
                fetch()
            })
        </script>

        <!-- JavaScript Libraries -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

        <script asp-append-version="true" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script asp-append-version="true" src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/chart/chart.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/easing/easing.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/waypoints/waypoints.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/owlcarousel/owl.carousel.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/tempusdominus/js/moment.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script asp-append-version="true" src="~/AdminFiles/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <script src="~/Client/services/tata-master/dist/tata.js"></script>
        <script src="~/Client/services/tata-master/dist/index.js"></script>

        @*SWAL LINK*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" integrity="sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


        <!-- Include a polyfill for ES6 Promises (optional) for IE11 and Android browser -->
        @*SWAL LINK*@

        <!-- Template Javascript -->
    <script asp-append-version="true" src="~/AdminFiles/js/main.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
    </html>
}