WebApp/Controllers/LabourController.cs
using BusinessAccess;
using DataAccess;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace WebApp
{

    [Route("labour")]
    public class LabourController : Controller
    {
        
        private readonly LabourManager labourManager;

        public LabourController(LabourRepository labourRepository)
        {
            labourManager = new LabourManager(labourRepository);
        }



        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public IActionResult Profile()
        {

            return View();
        }




        [HttpGet("managers")]
        public IActionResult Managers()
        {
            GeneralRequestModel generalRequestModel = new GeneralRequestModel()
            {
                generalResponses = labourManager.GetManagers(),


            };
            return View(generalRequestModel);
        }




        [HttpPost]
        public IActionResult SendRequest(RequestDb requestDb)
        {

            GeneralRequestModel generalRequestModel = new GeneralRequestModel()
            {
                returnValue = labourManager.SendRequest(requestDb),

            };
            return RedirectToAction("Managers", generalRequestModel);
        }



        [HttpGet("requests")]
        public IActionResult Requests()
        {
            Guid id = User.GetUserId();
            return View(labourManager.GetRequests(id));
        }

        [HttpGet("delete")]
        public IActionResult DeleteRequest(Guid id)
        {

            return RedirectToAction("Requests", labourManager.DeletebyId(id));

        }


        [HttpGet("colabrequests")]
        public IActionResult ColabRequests()
        {
            Guid id = User.GetUserId();
            return View(labourManager.GetColabRequests(id));
        }


        [HttpGet("approverequest")]
        public IActionResult ApproveRequest(Guid senderId)
        {
            Guid currentUserId = User.GetUserId();
            ViewBag.ApproveResponse = labourManager.ApproveColabRequest(senderId, currentUserId);
            return RedirectToAction(nameof(ColabRequests));
        }


    }
}

WebApp/Controllers/ManagerController.cs
using BusinessAccess;
using DataAccess;
using Microsoft.AspNetCore.Mvc;
using Models;

namespace WebApp
{
    [Route("Manager")]
    public class ManagerController : Controller
    {
        readonly ManagerRoleManager roleManager;

        public ManagerController(ManagerRepository managerRepository)
        {
            roleManager = new ManagerRoleManager(managerRepository);
        }

        [HttpGet("index")]
        public IActionResult Index()
        {
            return View();
        }



        [HttpGet("Contractors")]
        public IActionResult Contractors()
        {
            GeneralRequestModel generalRequestModel = new GeneralRequestModel()
            {
                generalResponses = roleManager.GetContractors()
            };

            return View(generalRequestModel);
        }


        [HttpPost]
        public IActionResult SendRequest(RequestDb requestDb)
        {

            GeneralRequestModel generalRequestModel = new GeneralRequestModel()
            {
                returnValue = roleManager.SendRequest(requestDb),

            };
            return RedirectToAction("Contractors", generalRequestModel);
        }


        [HttpGet]
        public IActionResult Requests()
        {
            Guid id = User.GetUserId();
            return View(roleManager.GetRequests(id));
        }

        [HttpGet("ulabours")]
        public IActionResult UnassignedLabours()
        {
            GeneralRequestModel generalRequestModel = new GeneralRequestModel()
            {
                userResponses = roleManager.UnassignedLabours().ToList()
            };

            return View(generalRequestModel);
        }

        [HttpPost("sendrequest")]
        public IActionResult SendLabourRequest(RequestDb requestDb)
        {
            GeneralRequestModel generalRequestModel = new GeneralRequestModel()
            {
                returnValue = roleManager.SendLabourRequest(requestDb),
            };
            return RedirectToAction("", generalRequestModel);
        }

        [HttpGet("getrequest")]
        public IActionResult GetLabourRequestt(Guid id)
        {
            var lbr = roleManager.GetLabourRequests(id);
            return View();
        }


        [HttpGet("assignedlabours")]
        public IActionResult GetAssignedLabours()
        {
            var id = User.GetUserId();
            List<UserResponse> userResponse = roleManager.AssignedLabour(id).ToList();
            return View(userResponse);
        }

        //[HttpPost("attendances")]
        //public IActionResult Attendance(UserAttendance userAttendance)
        //{
        //    Guid id = User.GetUserId();
        //    var res = roleManager.LabourAttendance(userAttendance);
        //    return View();
        //}

        [HttpPost("timein")]
        public IActionResult TimeIn(Guid labourId)
        {
            
            var res  = roleManager.TimeIn(labourId);
            return RedirectToAction(nameof(GetAssignedLabours));
        }

        [HttpPost("timeout")]
        public IActionResult TimeOut(Guid labourId)
        {
            var res = roleManager.TimeOut(labourId);
            return RedirectToAction(nameof(GetAssignedLabours));
        }

        [HttpPost("attendance")]
        public IActionResult GetAttendance(Guid labourId)
        {
            var attendance = roleManager.GetAttendance(labourId);
            return View(attendance);
        }

    }
}

WebApp/Views/Labour/ColabRequests.cshtml
@model IEnumerable<ResponseDb>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Role</th>
        <th>Message</th>
        <th>Action</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SenderUsername</td>
            <td>@item.SenderUserRole</td>
            <td>@item.Description</td>
            <td><a asp-action="ApproveRequest" asp-controller="Labour" asp-route-senderId=@item.SenderId class="btn btn-success">Accept</a></td>
            <td>
                <a asp-action="DeleteRequest" asp-controller="Labour" asp-route-id="@item.Id" class="btn btn-danger" onclick="return confirm('Are you sure you want to reject this request?');">Reject</a>
            </td>
        </tr>
    }
</table>


@*  onclick="return confirm('Are you sure you want to delete this item?');"*@

WebApp/Views/Labour/Index.cshtml
@model TestimonialRequest

<h1 style="margin-top:110px;text-align:center">Index Page</h1>
<partial name="_TestimonialPartial" model="Model"/>

WebApp/Views/Labour/Managers.cshtml
@model GeneralRequestModel

<table class="table table-hover">

    <tr>
        <td>Name</td>
        <td>Address</td>
        <td>Role</td>
        <td>Action</td>
    </tr>
    @foreach (var item in Model.generalResponses)
    {
        
        <tr>
            <td>@item.UserName</td>
            <td>@item.Address</td>
            <td>@item.UserRole</td>
            <td>
                     <div>

                    <form asp-action="SendRequest" asp-controller="Labour" method="post">

                        <input asp-for="requestDb.SenderId" hidden value="@User.GetUserId()">
                        <input asp-for="requestDb.RecieverId" hidden value="@item.Id">
                        <input asp-for="requestDb.SenderUsername" hidden value="@User.GetUserName()">
                        <input asp-for="requestDb.RecieverUsername" hidden value="@item.UserName">
                        <input asp-for="requestDb.SenderUserRole" hidden value="@User.GetRole()">
                        <input asp-for="requestDb.RecieverUserRole" hidden value="@item.UserRole">
                        <input asp-for="requestDb.Id" hidden>

                        <input asp-for="requestDb.RecieverName" readonly value="@item.Name" hidden>
                        
                        <textarea asp-for="requestDb.Description" class="form-control" rows="1" cols="5" placeholder="Send Request to @item.UserName" required="required">

                         </textarea>
                       
                        <button type="submit" class="btn btn-primary mt-1">
                            Request
                        </button>
                    </form>
                </div>
            </td>
        </tr>

    }

</table>

WebApp/Views/Labour/Requests.cshtml
@model IEnumerable<ResponseDb>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Role</th>
        <th>Message</th>
        <th>Action</th>
        <th>Action</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SenderUsername</td>
            <td>@item.SenderUserRole</td>
            <td>@item.Description</td>
            <td><button type="submit" class="btn btn-success">Accept</button></td>
            <td>
                <a asp-action="DeleteRequest" asp-controller="Labour" asp-route-id="@item.Id" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?');">Delete</a>
            </td>
        </tr>
    }
</table>


@*  onclick="return confirm('Are you sure you want to delete this item?');"*@